properties = dict[str,set[str]]()

properties["aws::ec2::instance"] = {
    "AdditionalInfo" ,
    "Affinity" ,
    "AvailabilityZone" ,
    "BlockDeviceMappings" ,
    "CpuOptions" ,
    "CreditSpecification" ,
    "DisableApiTermination" ,
    "EbsOptimized" ,
    "ElasticGpuSpecifications" ,
    "ElasticInferenceAccelerators" ,
    "EnclaveOptions" ,
    "HibernationOptions" ,
    "HostId" ,
    "HostResourceGroupArn" ,
    "IamInstanceProfile" ,
    "ImageId" ,
    "InstanceInitiatedShutdownBehavior" ,
    "InstanceType" ,
    "Ipv6AddressCount" ,
    "Ipv6Addresses" ,
    "KernelId" ,
    "KeyName" ,
    "LaunchTemplate" ,
    "LicenseSpecifications" ,
    "Monitoring" ,
    "NetworkInterfaces" ,
    "PlacementGroupName" ,
    "PrivateDnsNameOptions" ,
    "PrivateIpAddress" ,
    "PropagateTagsToVolumeOnCreation" ,
    "RamdiskId" ,
    "SecurityGroupIds" ,
    "SecurityGroups" ,
    "SourceDestCheck" ,
    "SsmAssociations" ,
    "SubnetId" ,
    "Tags" ,
    "Tenancy" ,
    "UserData" ,
    "Volumes" ,
    "InstanceId" ,
    "PrivateDnsName" ,
    "PrivateIp" ,
    "PublicDnsName" ,
    "PublicIp",
    "VpcId"
}

if __name__ == "__main__":
    pass